### ISSUE TITLE
Error Installing Vonk.Fhir.R4 nuget package

### ISSUE THREAD

**Issue by tvsports86** [FirelyTeam/firely-docs-firely-server#26]
When attempting to install the Vonk.Fhir.R4, R3 or R5 packages I receive the following error. (I have successfully added Vonk.Core)

Install-Package : NU1101: Unable to find package Vonk.Administration.Api. No packages exist with this id in source(s): DevExpress, DevExpress 18.1 
Local, DevExpress 19.1 Local, Microsoft Visual Studio Offline Packages, nuget.org
At line:1 char:1
+ Install-Package Vonk.Fhir.R3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by alexzautke** [comment]
Hi @tvsports86,

thanks to bringing this issue to our attention. It's unfortunately a bug that we missed in our release testing. It will be fixed in the next version of Firely Server (4.5.0). I'm afraid that there is currently no workaround. The last version of the package that should be usable is v4.3.0.
